// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelCompanyWebApi.Infrastructure.Context;

namespace TravelCompanyWebApi.Infrastructure.Migrations
{
    [DbContext(typeof(TravelCompanyDBContext))]
    [Migration("20210619115343_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Ukrainian_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte?>("ClimateId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClimateId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Climate", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Climates");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Duration", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte?>("Time")
                        .HasColumnType("tinyint")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.ToTable("Durations");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Pass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<double?>("FinalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("([dbo].[computeFinalPrice]([Id],[TourId],[Count]))", false);

                    b.Property<int?>("FullPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("([dbo].[computeFullPrice]([TourId],[Count]))", false);

                    b.Property<DateTime?>("PurchaseDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<double?>("TotalDiscount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("([dbo].[computeFullDiscount]([Id]))", false);

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TourId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.PassDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<int?>("PassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("PassId");

                    b.ToTable("PassDiscounts");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("DurationId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DurationId");

                    b.HasIndex("HotelId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.City", b =>
                {
                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.Climate", "Climate")
                        .WithMany("Cities")
                        .HasForeignKey("ClimateId")
                        .HasConstraintName("FK_Cities_Climates")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Cities_Countries")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Climate");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Hotel", b =>
                {
                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.City", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Hotels_Cities")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Pass", b =>
                {
                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.Client", "Client")
                        .WithMany("Passes")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK_Passes_Clients")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.Tour", "Tour")
                        .WithMany("Passes")
                        .HasForeignKey("TourId")
                        .HasConstraintName("FK_Passes_Tours")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.PassDiscount", b =>
                {
                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.Discount", "Discount")
                        .WithMany("PassDiscounts")
                        .HasForeignKey("DiscountId")
                        .HasConstraintName("FK_PassDiscounts_Discounts")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.Pass", "Pass")
                        .WithMany("PassDiscounts")
                        .HasForeignKey("PassId")
                        .HasConstraintName("FK_PassDiscounts_Passes")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Discount");

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Tour", b =>
                {
                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.Duration", "Duration")
                        .WithMany("Tours")
                        .HasForeignKey("DurationId")
                        .HasConstraintName("FK_Tours_Durations")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanyWebApi.Infrastructure.Entity.Hotel", "Hotel")
                        .WithMany("Tours")
                        .HasForeignKey("HotelId")
                        .HasConstraintName("FK_Tours_Hotels")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Duration");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.City", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Client", b =>
                {
                    b.Navigation("Passes");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Climate", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Discount", b =>
                {
                    b.Navigation("PassDiscounts");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Duration", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Hotel", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Pass", b =>
                {
                    b.Navigation("PassDiscounts");
                });

            modelBuilder.Entity("TravelCompanyWebApi.Infrastructure.Entity.Tour", b =>
                {
                    b.Navigation("Passes");
                });
#pragma warning restore 612, 618
        }
    }
}
